#!/usr/bin/perl
use feature qw/say/;
use Unicode::Collate::Locale;

binmode(STDERR, ":utf8");
binmode(STDOUT, ":utf8");
binmode(STDIN, ":utf8");

my %input;

while (<STDIN>) {
  my ($lemma) = /^.*?\[\[(.*?)\]\]/ or next;
  $input{$lemma} = $_;
}

my $coll = Unicode::Collate::Locale->new(
  locale   => "de_DE",
  variable => 'non-ignorable',
);

@lemmata = $coll->sort(keys %input);

@abc = qw/A B C D E F G H I J K L M N O P Q R S T U V W X Y Z/;
$buchstabe = shift @abc;
print "=== 0-9 ===\n";
  
while($lemma = shift @lemmata) {
  while ($buchstabe && $coll->cmp($lemma, $buchstabe) >= 0) {
    print "\n=== $buchstabe ===\n";
    $buchstabe = shift @abc;
  }
  print $input{$lemma};
}

while ($buchstabe = shift @abc) {
  print "\n=== $buchstabe ===\n";
}

