#!/usr/bin/perl

open DATEI, $ARGV[0];

binmode(STDERR, ":utf8");
binmode(STDOUT, ":utf8");
binmode(STDIN, ":utf8");
binmode(DATEI, ":utf8");

%filter;

while (<DATEI>) {
  /^\* *\[\[(.*?)\]\]/;
  $lemma = $1;
  $lemma =~ tr/_/ /;
  $filter{$lemma} = $_;
}


while (<STDIN>) {
  /^\* *\[\[(.*?)\]\]/;
  $lemma = $1;
  $lemma =~ tr/_/ /;
  if (defined $filter{$lemma}) {
    delete $filter{$lemma};
  } else {
    print $_;
  }
}

print STDERR sort values %filter;
