#!/usr/bin/perl

open DATEI, $ARGV[0];

binmode(STDERR, ":utf8");
binmode(STDOUT, ":utf8");
binmode(STDIN, ":utf8");
binmode(DATEI, ":utf8");

%filter;

while (<DATEI>) {
  /^:?\* *\[\[(.*?)\]\]/ or next;
  $lemma = $1;
  $lemma =~ tr/_/ /;
  $filter{$lemma} = $_;
}

my $filtered = 1;

while (<STDIN>) {
  if (/^:?\* *\[\[(.*?)\]\]/) {;
    $lemma = $1;
    $lemma =~ tr/_/ /;
    if (defined $filter{$lemma}) {
      delete $filter{$lemma};
      $filtered = 1;
    } else {
      print $_;
      $filtered = 0;
    }
  } elsif (/^:?:<nowiki>/) {
    print $_ unless $filtered;
  } else {
    print $_;
  }
    
}

print STDERR sort values %filter;
